//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace RankingForms.net.cloudapp.ottoservice {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IPPIJCloudService", Namespace="http://tempuri.org/")]
    public partial class PPIJCloudService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDataUsingDataContractOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPitanjeByIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMapaOdgovorByIDpitanjaOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSlikaOdgovorByIDpitanjaOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTekstOdgovorByIDpitanjaOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPitanjaByIDkategorijeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PPIJCloudService() {
            this.Url = "http://ottoservice.cloudapp.net/PPIJCloudService.svc";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetDataCompletedEventHandler GetDataCompleted;
        
        /// <remarks/>
        public event GetDataUsingDataContractCompletedEventHandler GetDataUsingDataContractCompleted;
        
        /// <remarks/>
        public event GetPitanjeByIDCompletedEventHandler GetPitanjeByIDCompleted;
        
        /// <remarks/>
        public event GetMapaOdgovorByIDpitanjaCompletedEventHandler GetMapaOdgovorByIDpitanjaCompleted;
        
        /// <remarks/>
        public event GetSlikaOdgovorByIDpitanjaCompletedEventHandler GetSlikaOdgovorByIDpitanjaCompleted;
        
        /// <remarks/>
        public event GetTekstOdgovorByIDpitanjaCompletedEventHandler GetTekstOdgovorByIDpitanjaCompleted;
        
        /// <remarks/>
        public event GetPitanjaByIDkategorijeCompletedEventHandler GetPitanjaByIDkategorijeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IPPIJCloudService/GetData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetData(int value, [System.Xml.Serialization.XmlIgnoreAttribute()] bool valueSpecified) {
            object[] results = this.Invoke("GetData", new object[] {
                        value,
                        valueSpecified});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataAsync(int value, bool valueSpecified) {
            this.GetDataAsync(value, valueSpecified, null);
        }
        
        /// <remarks/>
        public void GetDataAsync(int value, bool valueSpecified, object userState) {
            if ((this.GetDataOperationCompleted == null)) {
                this.GetDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataOperationCompleted);
            }
            this.InvokeAsync("GetData", new object[] {
                        value,
                        valueSpecified}, this.GetDataOperationCompleted, userState);
        }
        
        private void OnGetDataOperationCompleted(object arg) {
            if ((this.GetDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataCompleted(this, new GetDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IPPIJCloudService/GetDataUsingDataContract", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public CompositeType GetDataUsingDataContract([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] CompositeType composite) {
            object[] results = this.Invoke("GetDataUsingDataContract", new object[] {
                        composite});
            return ((CompositeType)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataUsingDataContractAsync(CompositeType composite) {
            this.GetDataUsingDataContractAsync(composite, null);
        }
        
        /// <remarks/>
        public void GetDataUsingDataContractAsync(CompositeType composite, object userState) {
            if ((this.GetDataUsingDataContractOperationCompleted == null)) {
                this.GetDataUsingDataContractOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataUsingDataContractOperationCompleted);
            }
            this.InvokeAsync("GetDataUsingDataContract", new object[] {
                        composite}, this.GetDataUsingDataContractOperationCompleted, userState);
        }
        
        private void OnGetDataUsingDataContractOperationCompleted(object arg) {
            if ((this.GetDataUsingDataContractCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataUsingDataContractCompleted(this, new GetDataUsingDataContractCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IPPIJCloudService/GetPitanjeByID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Pitanje GetPitanjeByID(int ID, [System.Xml.Serialization.XmlIgnoreAttribute()] bool IDSpecified) {
            object[] results = this.Invoke("GetPitanjeByID", new object[] {
                        ID,
                        IDSpecified});
            return ((Pitanje)(results[0]));
        }
        
        /// <remarks/>
        public void GetPitanjeByIDAsync(int ID, bool IDSpecified) {
            this.GetPitanjeByIDAsync(ID, IDSpecified, null);
        }
        
        /// <remarks/>
        public void GetPitanjeByIDAsync(int ID, bool IDSpecified, object userState) {
            if ((this.GetPitanjeByIDOperationCompleted == null)) {
                this.GetPitanjeByIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPitanjeByIDOperationCompleted);
            }
            this.InvokeAsync("GetPitanjeByID", new object[] {
                        ID,
                        IDSpecified}, this.GetPitanjeByIDOperationCompleted, userState);
        }
        
        private void OnGetPitanjeByIDOperationCompleted(object arg) {
            if ((this.GetPitanjeByIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPitanjeByIDCompleted(this, new GetPitanjeByIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IPPIJCloudService/GetMapaOdgovorByIDpitanja", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MapaOdgovor GetMapaOdgovorByIDpitanja(int ID, [System.Xml.Serialization.XmlIgnoreAttribute()] bool IDSpecified) {
            object[] results = this.Invoke("GetMapaOdgovorByIDpitanja", new object[] {
                        ID,
                        IDSpecified});
            return ((MapaOdgovor)(results[0]));
        }
        
        /// <remarks/>
        public void GetMapaOdgovorByIDpitanjaAsync(int ID, bool IDSpecified) {
            this.GetMapaOdgovorByIDpitanjaAsync(ID, IDSpecified, null);
        }
        
        /// <remarks/>
        public void GetMapaOdgovorByIDpitanjaAsync(int ID, bool IDSpecified, object userState) {
            if ((this.GetMapaOdgovorByIDpitanjaOperationCompleted == null)) {
                this.GetMapaOdgovorByIDpitanjaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMapaOdgovorByIDpitanjaOperationCompleted);
            }
            this.InvokeAsync("GetMapaOdgovorByIDpitanja", new object[] {
                        ID,
                        IDSpecified}, this.GetMapaOdgovorByIDpitanjaOperationCompleted, userState);
        }
        
        private void OnGetMapaOdgovorByIDpitanjaOperationCompleted(object arg) {
            if ((this.GetMapaOdgovorByIDpitanjaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMapaOdgovorByIDpitanjaCompleted(this, new GetMapaOdgovorByIDpitanjaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IPPIJCloudService/GetSlikaOdgovorByIDpitanja", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SlikaOdgovor GetSlikaOdgovorByIDpitanja(int ID, [System.Xml.Serialization.XmlIgnoreAttribute()] bool IDSpecified) {
            object[] results = this.Invoke("GetSlikaOdgovorByIDpitanja", new object[] {
                        ID,
                        IDSpecified});
            return ((SlikaOdgovor)(results[0]));
        }
        
        /// <remarks/>
        public void GetSlikaOdgovorByIDpitanjaAsync(int ID, bool IDSpecified) {
            this.GetSlikaOdgovorByIDpitanjaAsync(ID, IDSpecified, null);
        }
        
        /// <remarks/>
        public void GetSlikaOdgovorByIDpitanjaAsync(int ID, bool IDSpecified, object userState) {
            if ((this.GetSlikaOdgovorByIDpitanjaOperationCompleted == null)) {
                this.GetSlikaOdgovorByIDpitanjaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSlikaOdgovorByIDpitanjaOperationCompleted);
            }
            this.InvokeAsync("GetSlikaOdgovorByIDpitanja", new object[] {
                        ID,
                        IDSpecified}, this.GetSlikaOdgovorByIDpitanjaOperationCompleted, userState);
        }
        
        private void OnGetSlikaOdgovorByIDpitanjaOperationCompleted(object arg) {
            if ((this.GetSlikaOdgovorByIDpitanjaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSlikaOdgovorByIDpitanjaCompleted(this, new GetSlikaOdgovorByIDpitanjaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IPPIJCloudService/GetTekstOdgovorByIDpitanja", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public TekstOdgovor GetTekstOdgovorByIDpitanja(int ID, [System.Xml.Serialization.XmlIgnoreAttribute()] bool IDSpecified) {
            object[] results = this.Invoke("GetTekstOdgovorByIDpitanja", new object[] {
                        ID,
                        IDSpecified});
            return ((TekstOdgovor)(results[0]));
        }
        
        /// <remarks/>
        public void GetTekstOdgovorByIDpitanjaAsync(int ID, bool IDSpecified) {
            this.GetTekstOdgovorByIDpitanjaAsync(ID, IDSpecified, null);
        }
        
        /// <remarks/>
        public void GetTekstOdgovorByIDpitanjaAsync(int ID, bool IDSpecified, object userState) {
            if ((this.GetTekstOdgovorByIDpitanjaOperationCompleted == null)) {
                this.GetTekstOdgovorByIDpitanjaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTekstOdgovorByIDpitanjaOperationCompleted);
            }
            this.InvokeAsync("GetTekstOdgovorByIDpitanja", new object[] {
                        ID,
                        IDSpecified}, this.GetTekstOdgovorByIDpitanjaOperationCompleted, userState);
        }
        
        private void OnGetTekstOdgovorByIDpitanjaOperationCompleted(object arg) {
            if ((this.GetTekstOdgovorByIDpitanjaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTekstOdgovorByIDpitanjaCompleted(this, new GetTekstOdgovorByIDpitanjaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IPPIJCloudService/GetPitanjaByIDkategorije", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Pitanje GetPitanjaByIDkategorije(int ID, [System.Xml.Serialization.XmlIgnoreAttribute()] bool IDSpecified) {
            object[] results = this.Invoke("GetPitanjaByIDkategorije", new object[] {
                        ID,
                        IDSpecified});
            return ((Pitanje)(results[0]));
        }
        
        /// <remarks/>
        public void GetPitanjaByIDkategorijeAsync(int ID, bool IDSpecified) {
            this.GetPitanjaByIDkategorijeAsync(ID, IDSpecified, null);
        }
        
        /// <remarks/>
        public void GetPitanjaByIDkategorijeAsync(int ID, bool IDSpecified, object userState) {
            if ((this.GetPitanjaByIDkategorijeOperationCompleted == null)) {
                this.GetPitanjaByIDkategorijeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPitanjaByIDkategorijeOperationCompleted);
            }
            this.InvokeAsync("GetPitanjaByIDkategorije", new object[] {
                        ID,
                        IDSpecified}, this.GetPitanjaByIDkategorijeOperationCompleted, userState);
        }
        
        private void OnGetPitanjaByIDkategorijeOperationCompleted(object arg) {
            if ((this.GetPitanjaByIDkategorijeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPitanjaByIDkategorijeCompleted(this, new GetPitanjaByIDkategorijeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/PPIJServiceWebRole")]
    public partial class CompositeType {
        
        private bool boolValueField;
        
        private bool boolValueFieldSpecified;
        
        private string stringValueField;
        
        /// <remarks/>
        public bool BoolValue {
            get {
                return this.boolValueField;
            }
            set {
                this.boolValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BoolValueSpecified {
            get {
                return this.boolValueFieldSpecified;
            }
            set {
                this.boolValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StringValue {
            get {
                return this.stringValueField;
            }
            set {
                this.stringValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/PPIJServiceWebRole")]
    public partial class TekstOdgovor {
        
        private int broj_tocnog_odgovoraField;
        
        private bool broj_tocnog_odgovoraFieldSpecified;
        
        private int id_odgovoraField;
        
        private bool id_odgovoraFieldSpecified;
        
        private int id_pitanjaField;
        
        private bool id_pitanjaFieldSpecified;
        
        private int id_tipa_odgovoraField;
        
        private bool id_tipa_odgovoraFieldSpecified;
        
        private string tekst_1Field;
        
        private string tekst_2Field;
        
        private string tekst_3Field;
        
        private string tekst_4Field;
        
        /// <remarks/>
        public int broj_tocnog_odgovora {
            get {
                return this.broj_tocnog_odgovoraField;
            }
            set {
                this.broj_tocnog_odgovoraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool broj_tocnog_odgovoraSpecified {
            get {
                return this.broj_tocnog_odgovoraFieldSpecified;
            }
            set {
                this.broj_tocnog_odgovoraFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int id_odgovora {
            get {
                return this.id_odgovoraField;
            }
            set {
                this.id_odgovoraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool id_odgovoraSpecified {
            get {
                return this.id_odgovoraFieldSpecified;
            }
            set {
                this.id_odgovoraFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int id_pitanja {
            get {
                return this.id_pitanjaField;
            }
            set {
                this.id_pitanjaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool id_pitanjaSpecified {
            get {
                return this.id_pitanjaFieldSpecified;
            }
            set {
                this.id_pitanjaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int id_tipa_odgovora {
            get {
                return this.id_tipa_odgovoraField;
            }
            set {
                this.id_tipa_odgovoraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool id_tipa_odgovoraSpecified {
            get {
                return this.id_tipa_odgovoraFieldSpecified;
            }
            set {
                this.id_tipa_odgovoraFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string tekst_1 {
            get {
                return this.tekst_1Field;
            }
            set {
                this.tekst_1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string tekst_2 {
            get {
                return this.tekst_2Field;
            }
            set {
                this.tekst_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string tekst_3 {
            get {
                return this.tekst_3Field;
            }
            set {
                this.tekst_3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string tekst_4 {
            get {
                return this.tekst_4Field;
            }
            set {
                this.tekst_4Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/PPIJServiceWebRole")]
    public partial class SlikaOdgovor {
        
        private int broj_tocnog_odgovoraField;
        
        private bool broj_tocnog_odgovoraFieldSpecified;
        
        private int id_odgovoraField;
        
        private bool id_odgovoraFieldSpecified;
        
        private int id_pitanjaField;
        
        private bool id_pitanjaFieldSpecified;
        
        private int id_tipa_odgovoraField;
        
        private bool id_tipa_odgovoraFieldSpecified;
        
        private string slika_1Field;
        
        private string slika_2Field;
        
        private string slika_3Field;
        
        private string slika_4Field;
        
        /// <remarks/>
        public int broj_tocnog_odgovora {
            get {
                return this.broj_tocnog_odgovoraField;
            }
            set {
                this.broj_tocnog_odgovoraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool broj_tocnog_odgovoraSpecified {
            get {
                return this.broj_tocnog_odgovoraFieldSpecified;
            }
            set {
                this.broj_tocnog_odgovoraFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int id_odgovora {
            get {
                return this.id_odgovoraField;
            }
            set {
                this.id_odgovoraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool id_odgovoraSpecified {
            get {
                return this.id_odgovoraFieldSpecified;
            }
            set {
                this.id_odgovoraFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int id_pitanja {
            get {
                return this.id_pitanjaField;
            }
            set {
                this.id_pitanjaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool id_pitanjaSpecified {
            get {
                return this.id_pitanjaFieldSpecified;
            }
            set {
                this.id_pitanjaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int id_tipa_odgovora {
            get {
                return this.id_tipa_odgovoraField;
            }
            set {
                this.id_tipa_odgovoraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool id_tipa_odgovoraSpecified {
            get {
                return this.id_tipa_odgovoraFieldSpecified;
            }
            set {
                this.id_tipa_odgovoraFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string slika_1 {
            get {
                return this.slika_1Field;
            }
            set {
                this.slika_1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string slika_2 {
            get {
                return this.slika_2Field;
            }
            set {
                this.slika_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string slika_3 {
            get {
                return this.slika_3Field;
            }
            set {
                this.slika_3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string slika_4 {
            get {
                return this.slika_4Field;
            }
            set {
                this.slika_4Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/PPIJServiceWebRole")]
    public partial class MapaOdgovor {
        
        private string drzavaField;
        
        private int id_odgovoraField;
        
        private bool id_odgovoraFieldSpecified;
        
        private int id_pitanjaField;
        
        private bool id_pitanjaFieldSpecified;
        
        private int id_tipa_odgovoraField;
        
        private bool id_tipa_odgovoraFieldSpecified;
        
        private double koordinata_xField;
        
        private bool koordinata_xFieldSpecified;
        
        private double koordinata_yField;
        
        private bool koordinata_yFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string drzava {
            get {
                return this.drzavaField;
            }
            set {
                this.drzavaField = value;
            }
        }
        
        /// <remarks/>
        public int id_odgovora {
            get {
                return this.id_odgovoraField;
            }
            set {
                this.id_odgovoraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool id_odgovoraSpecified {
            get {
                return this.id_odgovoraFieldSpecified;
            }
            set {
                this.id_odgovoraFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int id_pitanja {
            get {
                return this.id_pitanjaField;
            }
            set {
                this.id_pitanjaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool id_pitanjaSpecified {
            get {
                return this.id_pitanjaFieldSpecified;
            }
            set {
                this.id_pitanjaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int id_tipa_odgovora {
            get {
                return this.id_tipa_odgovoraField;
            }
            set {
                this.id_tipa_odgovoraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool id_tipa_odgovoraSpecified {
            get {
                return this.id_tipa_odgovoraFieldSpecified;
            }
            set {
                this.id_tipa_odgovoraFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double koordinata_x {
            get {
                return this.koordinata_xField;
            }
            set {
                this.koordinata_xField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool koordinata_xSpecified {
            get {
                return this.koordinata_xFieldSpecified;
            }
            set {
                this.koordinata_xFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double koordinata_y {
            get {
                return this.koordinata_yField;
            }
            set {
                this.koordinata_yField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool koordinata_ySpecified {
            get {
                return this.koordinata_yFieldSpecified;
            }
            set {
                this.koordinata_yFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/PPIJServiceWebRole")]
    public partial class Pitanje {
        
        private int id_kategorijeField;
        
        private bool id_kategorijeFieldSpecified;
        
        private int id_odgovoraField;
        
        private bool id_odgovoraFieldSpecified;
        
        private int id_pitanjaField;
        
        private bool id_pitanjaFieldSpecified;
        
        private int id_tipa_odgovoraField;
        
        private bool id_tipa_odgovoraFieldSpecified;
        
        private string opis_podrucjaField;
        
        private string slika_pitanjaField;
        
        private string tekst_pitanjaField;
        
        /// <remarks/>
        public int id_kategorije {
            get {
                return this.id_kategorijeField;
            }
            set {
                this.id_kategorijeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool id_kategorijeSpecified {
            get {
                return this.id_kategorijeFieldSpecified;
            }
            set {
                this.id_kategorijeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int id_odgovora {
            get {
                return this.id_odgovoraField;
            }
            set {
                this.id_odgovoraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool id_odgovoraSpecified {
            get {
                return this.id_odgovoraFieldSpecified;
            }
            set {
                this.id_odgovoraFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int id_pitanja {
            get {
                return this.id_pitanjaField;
            }
            set {
                this.id_pitanjaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool id_pitanjaSpecified {
            get {
                return this.id_pitanjaFieldSpecified;
            }
            set {
                this.id_pitanjaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int id_tipa_odgovora {
            get {
                return this.id_tipa_odgovoraField;
            }
            set {
                this.id_tipa_odgovoraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool id_tipa_odgovoraSpecified {
            get {
                return this.id_tipa_odgovoraFieldSpecified;
            }
            set {
                this.id_tipa_odgovoraFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string opis_podrucja {
            get {
                return this.opis_podrucjaField;
            }
            set {
                this.opis_podrucjaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string slika_pitanja {
            get {
                return this.slika_pitanjaField;
            }
            set {
                this.slika_pitanjaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string tekst_pitanja {
            get {
                return this.tekst_pitanjaField;
            }
            set {
                this.tekst_pitanjaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetDataCompletedEventHandler(object sender, GetDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetDataUsingDataContractCompletedEventHandler(object sender, GetDataUsingDataContractCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataUsingDataContractCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataUsingDataContractCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CompositeType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CompositeType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetPitanjeByIDCompletedEventHandler(object sender, GetPitanjeByIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPitanjeByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPitanjeByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Pitanje Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Pitanje)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetMapaOdgovorByIDpitanjaCompletedEventHandler(object sender, GetMapaOdgovorByIDpitanjaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMapaOdgovorByIDpitanjaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMapaOdgovorByIDpitanjaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MapaOdgovor Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MapaOdgovor)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetSlikaOdgovorByIDpitanjaCompletedEventHandler(object sender, GetSlikaOdgovorByIDpitanjaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSlikaOdgovorByIDpitanjaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSlikaOdgovorByIDpitanjaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SlikaOdgovor Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SlikaOdgovor)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetTekstOdgovorByIDpitanjaCompletedEventHandler(object sender, GetTekstOdgovorByIDpitanjaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTekstOdgovorByIDpitanjaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTekstOdgovorByIDpitanjaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TekstOdgovor Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TekstOdgovor)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetPitanjaByIDkategorijeCompletedEventHandler(object sender, GetPitanjaByIDkategorijeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPitanjaByIDkategorijeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPitanjaByIDkategorijeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Pitanje Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Pitanje)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591