#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RankingForms.Resource", IsApplication=true)]

namespace RankingForms
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_in_top = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_out_bottom = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int slide_right = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int slide_up = 2130968579;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010010
			public const int ambientEnabled = 2130771984;
			
			// aapt resource value: 0x7f010014
			public const int buttonSize = 2130771988;
			
			// aapt resource value: 0x7f010001
			public const int cameraBearing = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int cameraTargetLat = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cameraTargetLng = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int cameraTilt = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cameraZoom = 2130771973;
			
			// aapt resource value: 0x7f010013
			public const int circleCrop = 2130771987;
			
			// aapt resource value: 0x7f010015
			public const int colorScheme = 2130771989;
			
			// aapt resource value: 0x7f010012
			public const int imageAspectRatio = 2130771986;
			
			// aapt resource value: 0x7f010011
			public const int imageAspectRatioAdjust = 2130771985;
			
			// aapt resource value: 0x7f010006
			public const int liteMode = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int mapType = 2130771968;
			
			// aapt resource value: 0x7f010016
			public const int scopeUris = 2130771990;
			
			// aapt resource value: 0x7f010007
			public const int uiCompass = 2130771975;
			
			// aapt resource value: 0x7f01000f
			public const int uiMapToolbar = 2130771983;
			
			// aapt resource value: 0x7f010008
			public const int uiRotateGestures = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int uiScrollGestures = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int uiTiltGestures = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int uiZoomControls = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int uiZoomGestures = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int useViewLifecycle = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int zOrderOnTop = 2130771982;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f06000e
			public const int common_action_bar_splitter = 2131099662;
			
			// aapt resource value: 0x7f060017
			public const int common_google_signin_btn_text_dark = 2131099671;
			
			// aapt resource value: 0x7f06000f
			public const int common_google_signin_btn_text_dark_default = 2131099663;
			
			// aapt resource value: 0x7f060011
			public const int common_google_signin_btn_text_dark_disabled = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int common_google_signin_btn_text_dark_focused = 2131099666;
			
			// aapt resource value: 0x7f060010
			public const int common_google_signin_btn_text_dark_pressed = 2131099664;
			
			// aapt resource value: 0x7f060018
			public const int common_google_signin_btn_text_light = 2131099672;
			
			// aapt resource value: 0x7f060013
			public const int common_google_signin_btn_text_light_default = 2131099667;
			
			// aapt resource value: 0x7f060015
			public const int common_google_signin_btn_text_light_disabled = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int common_google_signin_btn_text_light_focused = 2131099670;
			
			// aapt resource value: 0x7f060014
			public const int common_google_signin_btn_text_light_pressed = 2131099668;
			
			// aapt resource value: 0x7f060019
			public const int common_plus_signin_btn_text_dark = 2131099673;
			
			// aapt resource value: 0x7f060006
			public const int common_plus_signin_btn_text_dark_default = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int common_plus_signin_btn_text_dark_disabled = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int common_plus_signin_btn_text_dark_focused = 2131099657;
			
			// aapt resource value: 0x7f060007
			public const int common_plus_signin_btn_text_dark_pressed = 2131099655;
			
			// aapt resource value: 0x7f06001a
			public const int common_plus_signin_btn_text_light = 2131099674;
			
			// aapt resource value: 0x7f06000a
			public const int common_plus_signin_btn_text_light_default = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int common_plus_signin_btn_text_light_disabled = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int common_plus_signin_btn_text_light_focused = 2131099661;
			
			// aapt resource value: 0x7f06000b
			public const int common_plus_signin_btn_text_light_pressed = 2131099659;
			
			// aapt resource value: 0x7f060002
			public const int place_autocomplete_prediction_primary_text = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int place_autocomplete_prediction_primary_text_highlight = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int place_autocomplete_prediction_secondary_text = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int place_autocomplete_search_hint = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int place_autocomplete_search_text = 2131099648;
			
			// aapt resource value: 0x7f060005
			public const int place_autocomplete_separator = 2131099653;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070000
			public const int place_autocomplete_button_padding = 2131165184;
			
			// aapt resource value: 0x7f070008
			public const int place_autocomplete_powered_by_google_height = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int place_autocomplete_powered_by_google_start = 2131165193;
			
			// aapt resource value: 0x7f070003
			public const int place_autocomplete_prediction_height = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int place_autocomplete_prediction_horizontal_margin = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int place_autocomplete_prediction_primary_text = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int place_autocomplete_prediction_secondary_text = 2131165190;
			
			// aapt resource value: 0x7f070002
			public const int place_autocomplete_progress_horizontal_margin = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int place_autocomplete_progress_size = 2131165185;
			
			// aapt resource value: 0x7f070007
			public const int place_autocomplete_separator_start = 2131165191;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int aqua = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int aqua_question = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int buttonBlue = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int buttonDisabled = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int buttonGreen = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int buttonOrange = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int buttonPurple = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int buttonRed = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int buttonYellow = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_full_open_on_phone = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_google_signin_btn_icon_dark = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_google_signin_btn_icon_dark_disabled = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_google_signin_btn_icon_dark_focused = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_google_signin_btn_icon_dark_normal = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_google_signin_btn_icon_dark_pressed = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_google_signin_btn_icon_light = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_google_signin_btn_icon_light_disabled = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_google_signin_btn_icon_light_focused = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_google_signin_btn_icon_light_normal = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_google_signin_btn_icon_light_pressed = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_google_signin_btn_text_dark = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_google_signin_btn_text_dark_disabled = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_google_signin_btn_text_dark_focused = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_google_signin_btn_text_dark_normal = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_google_signin_btn_text_dark_pressed = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_google_signin_btn_text_light = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int common_google_signin_btn_text_light_disabled = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int common_google_signin_btn_text_light_focused = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int common_google_signin_btn_text_light_normal = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int common_google_signin_btn_text_light_pressed = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int common_ic_googleplayservices = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int common_plus_signin_btn_icon_dark = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int common_plus_signin_btn_icon_dark_disabled = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int common_plus_signin_btn_icon_dark_focused = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int common_plus_signin_btn_icon_dark_normal = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int common_plus_signin_btn_icon_dark_pressed = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int common_plus_signin_btn_icon_light = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int common_plus_signin_btn_icon_light_disabled = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int common_plus_signin_btn_icon_light_focused = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int common_plus_signin_btn_icon_light_normal = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int common_plus_signin_btn_icon_light_pressed = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int common_plus_signin_btn_text_dark = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int common_plus_signin_btn_text_dark_disabled = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int common_plus_signin_btn_text_dark_focused = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int common_plus_signin_btn_text_dark_normal = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int common_plus_signin_btn_text_dark_pressed = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int common_plus_signin_btn_text_light = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int common_plus_signin_btn_text_light_disabled = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int common_plus_signin_btn_text_light_focused = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int common_plus_signin_btn_text_light_normal = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int common_plus_signin_btn_text_light_pressed = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int edit_text_style = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int FORME = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int gMaps = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int Icon = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int logo = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int PITANJA = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int places_ic_clear = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int places_ic_search = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int powered_by_google_dark = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int powered_by_google_light = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int progress_bar_states = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int ProgressBarStyle = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int reddish = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int reddish_question = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int rsz_gmaps = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int rsz_main_menu_icon = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int rsz_maps2 = 2130837571;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0b004e
			public const int PlayerChooseList = 2131427406;
			
			// aapt resource value: 0x7f0b0005
			public const int adjust_height = 2131427333;
			
			// aapt resource value: 0x7f0b0006
			public const int adjust_width = 2131427334;
			
			// aapt resource value: 0x7f0b000a
			public const int auto = 2131427338;
			
			// aapt resource value: 0x7f0b001b
			public const int btnEnterPlayerNameSumbit = 2131427355;
			
			// aapt resource value: 0x7f0b0021
			public const int btnPoruka = 2131427361;
			
			// aapt resource value: 0x7f0b004f
			public const int buttonAddPlayerLocal = 2131427407;
			
			// aapt resource value: 0x7f0b0011
			public const int buttonCategory1 = 2131427345;
			
			// aapt resource value: 0x7f0b0012
			public const int buttonCategory2 = 2131427346;
			
			// aapt resource value: 0x7f0b0014
			public const int buttonCategory3 = 2131427348;
			
			// aapt resource value: 0x7f0b0015
			public const int buttonCategory4 = 2131427349;
			
			// aapt resource value: 0x7f0b0025
			public const int buttonFinalResultBack = 2131427365;
			
			// aapt resource value: 0x7f0b007b
			public const int buttonHighScore = 2131427451;
			
			// aapt resource value: 0x7f0b001f
			public const int buttonMapsClose = 2131427359;
			
			// aapt resource value: 0x7f0b0031
			public const int buttonMenu = 2131427377;
			
			// aapt resource value: 0x7f0b0035
			public const int buttonMenuAbout = 2131427381;
			
			// aapt resource value: 0x7f0b0033
			public const int buttonMenuNewGame = 2131427379;
			
			// aapt resource value: 0x7f0b0034
			public const int buttonMenuOptions = 2131427380;
			
			// aapt resource value: 0x7f0b007d
			public const int buttonMenuSP = 2131427453;
			
			// aapt resource value: 0x7f0b0029
			public const int buttonMenuWR = 2131427369;
			
			// aapt resource value: 0x7f0b0054
			public const int buttonMultiplayerChoose = 2131427412;
			
			// aapt resource value: 0x7f0b0041
			public const int buttonOptionAzuriraj = 2131427393;
			
			// aapt resource value: 0x7f0b0042
			public const int buttonOptionBackMenu = 2131427394;
			
			// aapt resource value: 0x7f0b0055
			public const int buttonPracticeChoose = 2131427413;
			
			// aapt resource value: 0x7f0b0030
			public const int buttonProceed = 2131427376;
			
			// aapt resource value: 0x7f0b007c
			public const int buttonProceedSP = 2131427452;
			
			// aapt resource value: 0x7f0b0061
			public const int buttonQuestionMapsOtvori = 2131427425;
			
			// aapt resource value: 0x7f0b005a
			public const int buttonQuestionMapsPicturePictureOtvori = 2131427418;
			
			// aapt resource value: 0x7f0b0057
			public const int buttonQuestionMapsPictureTitle = 2131427415;
			
			// aapt resource value: 0x7f0b005c
			public const int buttonQuestionMapsPictureZakljucaj = 2131427420;
			
			// aapt resource value: 0x7f0b005f
			public const int buttonQuestionMapsTitle = 2131427423;
			
			// aapt resource value: 0x7f0b0063
			public const int buttonQuestionMapsZakljucaj = 2131427427;
			
			// aapt resource value: 0x7f0b0069
			public const int buttonQuestionPictureA = 2131427433;
			
			// aapt resource value: 0x7f0b006a
			public const int buttonQuestionPictureB = 2131427434;
			
			// aapt resource value: 0x7f0b006c
			public const int buttonQuestionPictureC = 2131427436;
			
			// aapt resource value: 0x7f0b006d
			public const int buttonQuestionPictureD = 2131427437;
			
			// aapt resource value: 0x7f0b0066
			public const int buttonQuestionPictureTitle = 2131427430;
			
			// aapt resource value: 0x7f0b0072
			public const int buttonQuestionStandardA = 2131427442;
			
			// aapt resource value: 0x7f0b0073
			public const int buttonQuestionStandardB = 2131427443;
			
			// aapt resource value: 0x7f0b0075
			public const int buttonQuestionStandardC = 2131427445;
			
			// aapt resource value: 0x7f0b0076
			public const int buttonQuestionStandardD = 2131427446;
			
			// aapt resource value: 0x7f0b0070
			public const int buttonQuestionStandardTitle = 2131427440;
			
			// aapt resource value: 0x7f0b0053
			public const int buttonSinglePlayerChoose = 2131427411;
			
			// aapt resource value: 0x7f0b0050
			public const int buttonStartGameLocal = 2131427408;
			
			// aapt resource value: 0x7f0b000b
			public const int dark = 2131427339;
			
			// aapt resource value: 0x7f0b0000
			public const int hybrid = 2131427328;
			
			// aapt resource value: 0x7f0b0007
			public const int icon_only = 2131427335;
			
			// aapt resource value: 0x7f0b0058
			public const int imageViewQuestionMapsPicture = 2131427416;
			
			// aapt resource value: 0x7f0b0067
			public const int imageViewQuestionPicture = 2131427431;
			
			// aapt resource value: 0x7f0b007e
			public const int imageViewSplash = 2131427454;
			
			// aapt resource value: 0x7f0b000c
			public const int light = 2131427340;
			
			// aapt resource value: 0x7f0b0010
			public const int linearLayoutChoiceMenu = 2131427344;
			
			// aapt resource value: 0x7f0b0013
			public const int linearLayoutChoiceMenu2 = 2131427347;
			
			// aapt resource value: 0x7f0b0060
			public const int linearLayoutQuestionMaps = 2131427424;
			
			// aapt resource value: 0x7f0b0062
			public const int linearLayoutQuestionMaps2 = 2131427426;
			
			// aapt resource value: 0x7f0b0059
			public const int linearLayoutQuestionMapsPicture = 2131427417;
			
			// aapt resource value: 0x7f0b0068
			public const int linearLayoutQuestionPicture = 2131427432;
			
			// aapt resource value: 0x7f0b006b
			public const int linearLayoutQuestionPicture2 = 2131427435;
			
			// aapt resource value: 0x7f0b005b
			public const int linearLayoutQuestionPictureMaps2 = 2131427419;
			
			// aapt resource value: 0x7f0b0071
			public const int linearLayoutQuestionStandard = 2131427441;
			
			// aapt resource value: 0x7f0b0074
			public const int linearLayoutQuestionStandard2 = 2131427444;
			
			// aapt resource value: 0x7f0b001e
			public const int map = 2131427358;
			
			// aapt resource value: 0x7f0b0024
			public const int myFinalResult = 2131427364;
			
			// aapt resource value: 0x7f0b002f
			public const int myListView = 2131427375;
			
			// aapt resource value: 0x7f0b0019
			public const int myListViewChoiceMenu = 2131427353;
			
			// aapt resource value: 0x7f0b007a
			public const int myListViewSP = 2131427450;
			
			// aapt resource value: 0x7f0b0028
			public const int myListViewWR = 2131427368;
			
			// aapt resource value: 0x7f0b0001
			public const int none = 2131427329;
			
			// aapt resource value: 0x7f0b0002
			public const int normal = 2131427330;
			
			// aapt resource value: 0x7f0b0045
			public const int place_autocomplete_clear_button = 2131427397;
			
			// aapt resource value: 0x7f0b0047
			public const int place_autocomplete_powered_by_google = 2131427399;
			
			// aapt resource value: 0x7f0b0049
			public const int place_autocomplete_prediction_primary_text = 2131427401;
			
			// aapt resource value: 0x7f0b004a
			public const int place_autocomplete_prediction_secondary_text = 2131427402;
			
			// aapt resource value: 0x7f0b0048
			public const int place_autocomplete_progress = 2131427400;
			
			// aapt resource value: 0x7f0b0043
			public const int place_autocomplete_search_button = 2131427395;
			
			// aapt resource value: 0x7f0b0044
			public const int place_autocomplete_search_input = 2131427396;
			
			// aapt resource value: 0x7f0b0046
			public const int place_autocomplete_separator = 2131427398;
			
			// aapt resource value: 0x7f0b001c
			public const int progressBarLoading = 2131427356;
			
			// aapt resource value: 0x7f0b003e
			public const int radioButtonBrojPitanja10 = 2131427390;
			
			// aapt resource value: 0x7f0b003f
			public const int radioButtonBrojPitanja20 = 2131427391;
			
			// aapt resource value: 0x7f0b0040
			public const int radioButtonBrojPitanja25 = 2131427392;
			
			// aapt resource value: 0x7f0b003a
			public const int radioButtonTemaAqua = 2131427386;
			
			// aapt resource value: 0x7f0b0039
			public const int radioButtonTemaCoolBlack = 2131427385;
			
			// aapt resource value: 0x7f0b003b
			public const int radioButtonTemaReddish = 2131427387;
			
			// aapt resource value: 0x7f0b003d
			public const int radioGroupBrojPitanja = 2131427389;
			
			// aapt resource value: 0x7f0b0038
			public const int radioGroupTema = 2131427384;
			
			// aapt resource value: 0x7f0b0003
			public const int satellite = 2131427331;
			
			// aapt resource value: 0x7f0b0008
			public const int standard = 2131427336;
			
			// aapt resource value: 0x7f0b0004
			public const int terrain = 2131427332;
			
			// aapt resource value: 0x7f0b000d
			public const int textAboutTitle = 2131427341;
			
			// aapt resource value: 0x7f0b000e
			public const int textAboutUs = 2131427342;
			
			// aapt resource value: 0x7f0b0032
			public const int textGameTitle = 2131427378;
			
			// aapt resource value: 0x7f0b002d
			public const int textKrajIgre = 2131427373;
			
			// aapt resource value: 0x7f0b0078
			public const int textKrajIgreSP = 2131427448;
			
			// aapt resource value: 0x7f0b000f
			public const int textOdaberiKategoriju = 2131427343;
			
			// aapt resource value: 0x7f0b003c
			public const int textOptionBrojPitanja = 2131427388;
			
			// aapt resource value: 0x7f0b0037
			public const int textOptionTema = 2131427383;
			
			// aapt resource value: 0x7f0b0036
			public const int textOptionTitle = 2131427382;
			
			// aapt resource value: 0x7f0b004b
			public const int textPlayerChoosePlayer = 2131427403;
			
			// aapt resource value: 0x7f0b004c
			public const int textPlayerChooseTitle = 2131427404;
			
			// aapt resource value: 0x7f0b002b
			public const int textPlayerName = 2131427371;
			
			// aapt resource value: 0x7f0b002a
			public const int textPosition = 2131427370;
			
			// aapt resource value: 0x7f0b0064
			public const int textQuestionMapsCategory = 2131427428;
			
			// aapt resource value: 0x7f0b005d
			public const int textQuestionMapsPictureCategory = 2131427421;
			
			// aapt resource value: 0x7f0b0056
			public const int textQuestionMapsPictureTimer = 2131427414;
			
			// aapt resource value: 0x7f0b005e
			public const int textQuestionMapsTimer = 2131427422;
			
			// aapt resource value: 0x7f0b006e
			public const int textQuestionPictureCategory = 2131427438;
			
			// aapt resource value: 0x7f0b0065
			public const int textQuestionPictureTimer = 2131427429;
			
			// aapt resource value: 0x7f0b0077
			public const int textQuestionStandardCategory = 2131427447;
			
			// aapt resource value: 0x7f0b006f
			public const int textQuestionStandardTimer = 2131427439;
			
			// aapt resource value: 0x7f0b0022
			public const int textRezultatFinal = 2131427362;
			
			// aapt resource value: 0x7f0b0051
			public const int textSinMultPrac = 2131427409;
			
			// aapt resource value: 0x7f0b007f
			public const int textSplashTitle = 2131427455;
			
			// aapt resource value: 0x7f0b002c
			public const int textTotalScore = 2131427372;
			
			// aapt resource value: 0x7f0b0017
			public const int textViewPitanjeBr = 2131427351;
			
			// aapt resource value: 0x7f0b0016
			public const int textViewPitanjeBrTitle = 2131427350;
			
			// aapt resource value: 0x7f0b0052
			public const int textViewProgressBar = 2131427410;
			
			// aapt resource value: 0x7f0b0026
			public const int textWorldRanking = 2131427366;
			
			// aapt resource value: 0x7f0b0023
			public const int titleFinalResult = 2131427363;
			
			// aapt resource value: 0x7f0b0018
			public const int titleListChoiceMenu = 2131427352;
			
			// aapt resource value: 0x7f0b002e
			public const int titleListView = 2131427374;
			
			// aapt resource value: 0x7f0b0079
			public const int titleListViewSP = 2131427449;
			
			// aapt resource value: 0x7f0b0027
			public const int titleListViewWR = 2131427367;
			
			// aapt resource value: 0x7f0b004d
			public const int titlePlayerChooseLocal = 2131427405;
			
			// aapt resource value: 0x7f0b001a
			public const int txtEnterPlayerName = 2131427354;
			
			// aapt resource value: 0x7f0b001d
			public const int txtLoading = 2131427357;
			
			// aapt resource value: 0x7f0b0020
			public const int txtPoruka = 2131427360;
			
			// aapt resource value: 0x7f0b0009
			public const int wide = 2131427337;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f090000
			public const int google_play_services_version = 2131296256;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int about = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ChoiceMenu = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int dialog_enterPlayerName = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int dialog_loading = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int dialog_maps = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int dialog_poruka = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int FinalScoreList = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int HighScore = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int listview_row = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Main = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int main_menu = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int OptionsMenu = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int place_autocomplete_fragment = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int place_autocomplete_item_powered_by_google = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int place_autocomplete_item_prediction = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int place_autocomplete_progress = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int playerChoose_row = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int PlayerChooseLocal = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int playgame_menu = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int QuestionMapPicture = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int QuestionMaps = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int QuestionPicture = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int QuestionStandard = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int singlePlayerList = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int splash = 2130903064;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f050000
			public const int Click1 = 2131034112;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f080022
			public const int ApplicationName = 2131230754;
			
			// aapt resource value: 0x7f080021
			public const int Hello = 2131230753;
			
			// aapt resource value: 0x7f080003
			public const int auth_google_play_services_client_facebook_display_name = 2131230723;
			
			// aapt resource value: 0x7f080002
			public const int auth_google_play_services_client_google_display_name = 2131230722;
			
			// aapt resource value: 0x7f08001a
			public const int common_google_play_services_api_unavailable_text = 2131230746;
			
			// aapt resource value: 0x7f08000c
			public const int common_google_play_services_enable_button = 2131230732;
			
			// aapt resource value: 0x7f08000b
			public const int common_google_play_services_enable_text = 2131230731;
			
			// aapt resource value: 0x7f08000a
			public const int common_google_play_services_enable_title = 2131230730;
			
			// aapt resource value: 0x7f080009
			public const int common_google_play_services_install_button = 2131230729;
			
			// aapt resource value: 0x7f080007
			public const int common_google_play_services_install_text_phone = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int common_google_play_services_install_text_tablet = 2131230728;
			
			// aapt resource value: 0x7f080006
			public const int common_google_play_services_install_title = 2131230726;
			
			// aapt resource value: 0x7f080015
			public const int common_google_play_services_invalid_account_text = 2131230741;
			
			// aapt resource value: 0x7f080014
			public const int common_google_play_services_invalid_account_title = 2131230740;
			
			// aapt resource value: 0x7f080013
			public const int common_google_play_services_network_error_text = 2131230739;
			
			// aapt resource value: 0x7f080012
			public const int common_google_play_services_network_error_title = 2131230738;
			
			// aapt resource value: 0x7f080005
			public const int common_google_play_services_notification_ticker = 2131230725;
			
			// aapt resource value: 0x7f08001e
			public const int common_google_play_services_restricted_profile_text = 2131230750;
			
			// aapt resource value: 0x7f08001d
			public const int common_google_play_services_restricted_profile_title = 2131230749;
			
			// aapt resource value: 0x7f08001c
			public const int common_google_play_services_sign_in_failed_text = 2131230748;
			
			// aapt resource value: 0x7f08001b
			public const int common_google_play_services_sign_in_failed_title = 2131230747;
			
			// aapt resource value: 0x7f080004
			public const int common_google_play_services_unknown_issue = 2131230724;
			
			// aapt resource value: 0x7f080017
			public const int common_google_play_services_unsupported_text = 2131230743;
			
			// aapt resource value: 0x7f080016
			public const int common_google_play_services_unsupported_title = 2131230742;
			
			// aapt resource value: 0x7f080018
			public const int common_google_play_services_update_button = 2131230744;
			
			// aapt resource value: 0x7f08000e
			public const int common_google_play_services_update_text = 2131230734;
			
			// aapt resource value: 0x7f08000d
			public const int common_google_play_services_update_title = 2131230733;
			
			// aapt resource value: 0x7f080011
			public const int common_google_play_services_updating_text = 2131230737;
			
			// aapt resource value: 0x7f080010
			public const int common_google_play_services_updating_title = 2131230736;
			
			// aapt resource value: 0x7f08000f
			public const int common_google_play_services_wear_update_text = 2131230735;
			
			// aapt resource value: 0x7f080019
			public const int common_open_on_phone = 2131230745;
			
			// aapt resource value: 0x7f08001f
			public const int common_signin_button_text = 2131230751;
			
			// aapt resource value: 0x7f080020
			public const int common_signin_button_text_long = 2131230752;
			
			// aapt resource value: 0x7f080023
			public const int google_maps_key = 2131230755;
			
			// aapt resource value: 0x7f080001
			public const int place_autocomplete_clear_button = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int place_autocomplete_search_hint = 2131230720;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f0a0000
			public const int dialog_animation = 2131361792;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[] {
					2130771985,
					2130771986,
					2130771987};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] MapAttrs = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984};
			
			// aapt resource value: 16
			public const int MapAttrs_ambientEnabled = 16;
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 6
			public const int MapAttrs_liteMode = 6;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 7
			public const int MapAttrs_uiCompass = 7;
			
			// aapt resource value: 15
			public const int MapAttrs_uiMapToolbar = 15;
			
			// aapt resource value: 8
			public const int MapAttrs_uiRotateGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiScrollGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiTiltGestures = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomControls = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_uiZoomGestures = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_useViewLifecycle = 13;
			
			// aapt resource value: 14
			public const int MapAttrs_zOrderOnTop = 14;
			
			public static int[] SignInButton = new int[] {
					2130771988,
					2130771989,
					2130771990};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
